<a href="https://colab.research.google.com/github/mafenavas/GLAB_386_3_1_ACT_386_3_1/blob/main/m_navas_GLAB_386_3_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Guided Lab - 386.3.1 - Panda Series**



**Lab Objective and Overview:**

- In this lab, we will demonstrate the Panda Series data structure. The lab guides you through creating and manipulating Series using various methods. The Series is a fundamental component in data analysis with Pandas, offering a one-dimensional labeled array capable of holding various data types.

- Each example provides a clear demonstration of a specific concept.

**Key Topics**

- **Series Creation:** Learn how to create Series using dictionaries, scalar values, and NumPy arrays.

- **Indexing:** Understand how to select specific elements in a Series using labels.

- **Handling Missing Data:** Work with NaN (Not a Number) values that represent missing data.

**Learning Objective:**

By the end of this lab, you will be able to:
- Describe the concept of a Pandas Series.
- Create a Series from a dictionary, scalar value, and ndarray.
- Access and manipulate elements within a Series.
 - Utilize the Panda Series data structure.

**Submission**
- Submit your completed lab using the Start Assignment button on the assignment page in Canvas.
- Your submission can be include:
  - if you are using notebook then, all tasks should be written and submitted in a single notebook file, for example: (**your_name_labname.ipynb**).
  - if you are using python script file, all tasks should be written and submitted in a single python script file for example: **(your_name_labname.py)**.
- Add appropriate comments and any additional instructions if required.

**Introduction:**

Series is a one-dimensional labeled array capable of holding any data type (integers, strings, floating point numbers, Python objects, etc.). The axis labels are collectively referred to as the index. The basic method to create a Series is to call:

###**`newSeries = pd.Series (data,index)`**

Here, data can be many different things:

- a Python dict.

- an ndarray.
- a scalar value (like 5).

The passed index is a list of axis labels. Thus, this separates into a few cases depending on what data is:

---
## **Begin:**

## **Example 1: Creating Panda Series from Dictionary**

Series can be instantiated from dicts:

### **Example: 1.1**

In [ ]:
import pandas as pd
d = {"b": 1, "a": 0, "c": 2, "d":100}
pd.Series(d)

b      1
a      0
c      2
d    100
dtype: int64

### **Example: 1.2**

In [ ]:

import pandas as pd
d = {"a": 0.0, "b": 1.0, "c": 2.0}
pd.Series(d)

a    0.0
b    1.0
c    2.0
dtype: float64

### **Example: 1.3**

If an index is passed, the values in data corresponding to the labels in the index will be pulled out.

In [ ]:
pd.Series(d, index=["b", "c", "d", "a"])

b    1.0
c    2.0
d    NaN
a    0.0
dtype: float64

**Note:** NaN (not a number) is the standard missing data marker used in pandas.

##**Example 2: Key/Value Objects as Series**

**Example 2.1**

Note: The keys of the dictionary become the labels.

In [ ]:
import pandas as pd

calories = {"day1": 420, "day2": 380, "day3": 390}

myvar = pd.Series(calories)

print(myvar.loc['day1'])

print(myvar)

420
day1    420
day2    380
day3    390
dtype: int64

**Example 2.2**

To select only some of the items in the dictionary, use the index argument and specify only the items you want to include in the Series.


Create a Series using only data from "day1" and "day2":

In [ ]:
calories = {"day1": 420, "day2": 380, "day3": 390}
myvar = pd.Series(calories, index = ["day1", "day2"])
print(myvar)

day1    420
day2    380
dtype: int64

**Example 3:  Creating Panda Series from Scalar Value**

If data is a scalar value, an index must be provided. The value will be repeated to match the length of the index.

In [ ]:
pd.Series(5.0, index=["a", "b", "c", "d", "e"])

a    5.0
b    5.0
c    5.0
d    5.0
e    5.0
dtype: float64